### ISSUE TITLE
Build bottles for remaining renamed formulae

### ISSUE THREAD

**Issue by cartr** [cartr/homebrew-qt4#20]
"Essential" formulae: (high usage, long build times)
- [x] qt-webkit@2.3
- [x] shiboken@1.2
- [x] pyside@1.2
- [x] pyside-tools@1.2
- [ ] pyqt@4

Once these are done, I'll build bottles for the remaining formulae to ensure their build times are fast too.

**Comment by bblacey** [comment]
The lack of bottles, particularly the qt-webkit formula, are causing FreeCAD jobs on [Travis to fail](https://travis-ci.org/FreeCAD/FreeCAD/jobs/219367138#L486) due to excessive logging and/or build times.   What is the timeframe for preparing and deploying these bottles?

**Comment by cartr** [comment]
@bblacey Bottles for qt-webkit and PySide were been deployed earlier today, and should work with both the default Travis image and the one for macOS Sierra. I'll take a look at your build log to try and see what's happening.

**Comment by cartr** [comment]
@bblacey Ah, I see the issue: your builds are using the `xcode6.4` image on Yosemite, and my `qt-webkit@2.3` bottle build for Yosemite timed out. I've retried that build.

In the meantime, would it be possible to use a newer image? [Travis' docs page](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-6.4) says `xcode6.4` is deprecated and "will be retired" a few months ago. `xcode7.3` is Travis' default, and `xcode8.3` is the latest version.

**Comment by bblacey** [comment]
@cartr - thanks for the quick response.  Actually, we can't use a newer Xcode. We build on macOS 10.10 because we package and deploy our builds from Travis and need to support the earliest possible OS available.  Hombrew also supports 10.10+.

**Comment by cartr** [comment]
@bblacey I see. I've started a [new build](https://travis-ci.org/cartr/qt4-autobottler/jobs/219409309) of `qt-webkit@2.3` for Yosemite, which is currently in the queue, and will update you when it finishes.

Apologies for breaking FreeCAD's builds – unfortunately, I didn't have as much time as I'd hoped to get the bottle builds finished before merging the name change.

**Comment by bblacey** [comment]
@cartr - no worries...  I really appreciate your keeping Qt4 alive for the community and we will get through this speed bump.  That said, if your bottle builds are timing out, perhaps you can use environment variables to build one bottle per build matrix entry (i.e. one job per os per formula).  I think you would do it with something like this:

```
env:
   global:
   - HOMBREW_DEVELOPER="1"
   matrix:
   - FORMULA="pyside@1.2"
   - FORMULA="shiboken@1.2"
   - FORMULA=...

osx_image: 
   - xcode6.4
   - xcode7.3
   - xcode8.3

install:
   - brew update
   - brew tap cartr/qt4
   - brew install --only-dependencies --build-bottle cartr/qt4/${FORMULA}
   - travis_wait 90 brew install --build-bottle cartr/qt4/${FORMULA}
   - brew bottle cartr/qt4/${FORMULA}

deploy:
   - ...
```

That should create the following jobs:

pyside@1.2 on macOS 10.10
pyside@1.2 on macOS 10.11
pyside@1.2 on macOS 10.12
shiboken@1.2 on macOS 10.10
shiboken@1.2 on macOS 10.11
shiboken@1.2 on macOS 10.12

and so on...  Just add the complete list of formula to the env matrix to create all the os,bottle combinations so you can use the entire travis build time for a single os/bottle combination.

If you want to rebuild all the bottles, you can simply open travis and click restart on the last job and it will re-run all combinations or you can chose to restart only one of the the sub-jobs for a specific os/bottle combinations or the sub-jobs for a bottle for all oses, etc.  Basically, this gives you a GUI to rebuild/manage bottles vs. a text file that has be to committed and pushed to control bottle builds.

Just a thought.
